import AuthLayoutProvider from './Provider/Layout/AuthLayoutProvider'
import MainLayoutProvider from './Provider/Layout/MainLayoutProvider'
import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'HRM Software',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* <MainLayoutProvider> */}
          {/* <AuthLayoutProvider> */}
          {children}
          {/* </AuthLayoutProvider> */}
        {/* </MainLayoutProvider> */}
      </body>
    </html>
  )
}
